### ISSUE TITLE
Error while building the application on a windows machine

### ISSUE THREAD

**Issue by agarwalprashant** [sdras/cssgridgenerator#32]
Hi,

After running npm install, I ran  npm run serve and getting this error in my terminal.Also, I am running this application on windows 10 machine - 

cssgridgenerator-master\node_modules\open\index.js:11
const wslToWindowsPath = async path => {
                               ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\vn50afl\Desktop\cssgridgenerator-master\cssgridgenerator-master\node_modules\@vue\cli-shared-utils\lib\openBrowser.js:9:14)
    at Module._compile (module.js:570:32)

**Comment by agarwalprashant** [comment]
Can somebody help me figure out what is going wrong in building the application. Thanks :)

**Comment by pnevares** [comment]
Can you run `node -v` and comment with the version of Node.js you're running?

**Comment by agarwalprashant** [comment]
@pnevares  thanks for looking into this issue. Currently, I am running node version 6.9.2.

**Comment by ajerez** [comment]
> @pnevares thanks for looking into this issue. Currently, I am running node version 6.9.2.

Yo need at least Node 8.11.0 to run vue-cli, as the documentations says:
https://cli.vuejs.org/guide/installation.html

**Comment by agarwalprashant** [comment]
Thanks @ajerez. 👍  I just tried building the application with v10.15.0 and it worked. :)
